cabal-version:      3.0
name:               codegen
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             TurekJakub
maintainer:         jakubturek32@gmail.com
-- copyright:
category:           System
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

executable codegen
    import:           warnings
    main-is:          Main.hs
    other-modules: Ir, Codegen.Common, Codegen.Codegen, Target.Target,Target.Riscv.Common, Target.Riscv.Rv64, Target.Riscv.Rv32, Asm.Asm, Asm.Riscv, Demo
    -- other-extensions:
    build-depends:    base >= 4.19 && < 4.23, containers, mtl, optics, text, optparse-applicative, aeson, bytestring
    hs-source-dirs:   src
    default-language:   GHC2021
    default-extensions: GHC2024